development: &default
  adapter: postgresql
  database: mit_conjoint_development
  encoding: utf8
  host: localhost

test:
  <<: *default
  database: mit_conjoint_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
